/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {}
  interface MyHighChart {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyHighChartElement extends Components.MyHighChart, HTMLStencilElement {}
  var HTMLMyHighChartElement: {
    prototype: HTMLMyHighChartElement;
    new (): HTMLMyHighChartElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'my-high-chart': HTMLMyHighChartElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {}
  interface MyHighChart extends JSXBase.HTMLAttributes<HTMLMyHighChartElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'my-high-chart': MyHighChart;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


